# Generated by Django 5.0.1 on 2024-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=36)),
                ('purchase_price', models.IntegerField()),
                ('hold_period', models.IntegerField()),
                ('hold_period_m', models.IntegerField()),
                ('apartment_rent', models.IntegerField()),
                ('parking_rent', models.IntegerField()),
                ('renters_insurance', models.IntegerField()),
                ('monthly_rent', models.IntegerField()),
                ('rate_capital_gains', models.FloatField(max_length=4)),
                ('rate_federal_tax', models.FloatField(max_length=4)),
                ('bool_federal', models.BooleanField()),
                ('salt_limit', models.IntegerField()),
                ('bool_salt', models.BooleanField()),
                ('rent_growth', models.FloatField(max_length=4)),
                ('home_appreciation', models.FloatField(max_length=4)),
                ('ret_inflation', models.FloatField(max_length=4)),
                ('other_inflation', models.FloatField(max_length=4)),
                ('fee_inspection', models.IntegerField()),
                ('fee_appraisal', models.IntegerField()),
                ('fee_legal', models.IntegerField()),
                ('rate_title_insurance_aq', models.FloatField(max_length=4)),
                ('title_insurance_aq', models.FloatField(max_length=8)),
                ('lender_costs_other', models.IntegerField()),
                ('rate_transfer_tax_aq', models.FloatField(max_length=4)),
                ('transfer_tax_aq', models.FloatField(max_length=8)),
                ('total_acquisition', models.FloatField(max_length=8)),
                ('rate_title_insurance_dis', models.FloatField(max_length=4)),
                ('title_insurance_dis', models.FloatField(max_length=8)),
                ('rate_transfer_tax_dis', models.FloatField(max_length=4)),
                ('transfer_tax_dis', models.FloatField(max_length=8)),
                ('rate_brokerage', models.FloatField(max_length=8)),
                ('fee_brokerage', models.FloatField(max_length=4)),
                ('total_disposition', models.FloatField(max_length=9)),
                ('rate_property_tax', models.FloatField(max_length=4)),
                ('property_tax', models.FloatField(max_length=8)),
                ('rate_home_insurance', models.FloatField(max_length=4)),
                ('home_insurance', models.FloatField(max_length=8)),
                ('rate_home_maintenance', models.FloatField(max_length=4)),
                ('home_maintenance', models.FloatField(max_length=8)),
                ('rate_hoa_util', models.FloatField(max_length=4)),
                ('hoa_util', models.FloatField(max_length=6)),
                ('rate_ltv_max', models.IntegerField()),
                ('loan_ltv_max', models.IntegerField()),
                ('loan_ltv_desired', models.FloatField(max_length=8)),
                ('rate_ltv_desired', models.FloatField(max_length=4)),
                ('rate_home_loan', models.FloatField(max_length=4)),
                ('amort_home_loan', models.IntegerField()),
                ('rate_mortgage_insurance', models.FloatField(max_length=4)),
                ('clear_mortgage_insurance', models.IntegerField()),
                ('rate_mortgage_points', models.FloatField(max_length=4)),
                ('mortgage_points', models.FloatField(max_length=6)),
            ],
        ),
    ]
