# Generated by Django 5.0.1 on 2024-01-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
