# Generated by Django 5.0.1 on 2024-01-18 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datafield_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 2, 15, 35, 818291, tzinfo=datetime.timezone.utc)),
        ),
    ]
