# Generated by Django 5.0.1 on 2024-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datafield_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
