# Generated by Django 5.0.1 on 2024-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_datafield_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='pub_date',
        ),
    ]
