# Generated by Django 5.0.1 on 2024-01-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datafield_mcf_table_datafield_total_rcf'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='mcfu_gross_sale_30y',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='datafield',
            name='mcfu_table',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='datafield',
            name='total_uocf',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
