# Generated by Django 5.0.1 on 2024-01-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_datafield_mcfl_html_datafield_total_locf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='mcfu_gross_sale_30y',
            new_name='gross_sale_30y',
        ),
        migrations.RenameField(
            model_name='datafield',
            old_name='mcfl_html',
            new_name='mcfl_table',
        ),
    ]
