# Generated by Django 5.0.1 on 2024-02-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_datafield_mcfr_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafield',
            old_name='mcf_table',
            new_name='MCF',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='gross_sale_30y',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='mcfl_table',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='mcfr_table',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='mcfu_table',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='total_locf',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='total_rcf',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='total_uocf',
        ),
    ]
