# Generated by Django 5.0.1 on 2024-02-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_mcf_table_datafield_mcf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='ACF',
            field=models.TextField(default=''),
        ),
    ]
