# Generated by Django 5.0.1 on 2024-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_datafield_acf'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='mcf_interest',
            field=models.FloatField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
