# Generated by Django 5.0.1 on 2024-02-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_datafield_mcf_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='mcf_interest',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
