# Generated by Django 5.0.1 on 2024-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_datafield_mcf_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='total_interest',
            field=models.FloatField(default=0, max_length=8),
        ),
    ]
