# Generated by Django 5.0.1 on 2024-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_datafield_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='amortization',
            field=models.FloatField(default=4373, max_length=6),
        ),
        migrations.AddField(
            model_name='datafield',
            name='mortgage_insurance_payment',
            field=models.FloatField(default=40111, max_length=8),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='total_interest',
            field=models.FloatField(default=27861, max_length=8),
        ),
    ]
