# Generated by Django 5.0.1 on 2024-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_datafield_amortization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='initial_equity_GROSS',
            field=models.FloatField(default=11750, max_length=7),
        ),
        migrations.AddField(
            model_name='datafield',
            name='initial_equity_NOR',
            field=models.FloatField(default=11750, max_length=7),
        ),
    ]
