# Generated by Django 5.0.1 on 2024-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_datafield_initial_equity_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='lv_em_GROSS',
            field=models.FloatField(default=0.6, max_length=5),
        ),
        migrations.AddField(
            model_name='datafield',
            name='lv_em_NOR',
            field=models.FloatField(default=1.91, max_length=5),
        ),
        migrations.AddField(
            model_name='datafield',
            name='lv_irr_GROSS',
            field=models.FloatField(default=-0.144, max_length=5),
        ),
        migrations.AddField(
            model_name='datafield',
            name='lv_irr_NOR',
            field=models.FloatField(default=0.155, max_length=5),
        ),
        migrations.AddField(
            model_name='datafield',
            name='max_equity_GROSS',
            field=models.FloatField(default=281846, max_length=7),
        ),
        migrations.AddField(
            model_name='datafield',
            name='max_equity_NOR',
            field=models.FloatField(default=111750, max_length=7),
        ),
        migrations.AddField(
            model_name='datafield',
            name='profit_GROSS',
            field=models.FloatField(default=-111796, max_length=7),
        ),
        migrations.AddField(
            model_name='datafield',
            name='profit_NOR',
            field=models.FloatField(default=101631, max_length=7),
        ),
        migrations.AddField(
            model_name='datafield',
            name='unlv_irr_GROSS',
            field=models.FloatField(default=-0.07, max_length=5),
        ),
        migrations.AddField(
            model_name='datafield',
            name='unlv_irr_NOR',
            field=models.FloatField(default=0.076, max_length=5),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='initial_equity_GROSS',
            field=models.FloatField(default=111750, max_length=7),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='initial_equity_NOR',
            field=models.FloatField(default=111750, max_length=7),
        ),
    ]
